Update center.sh
The current implementation does not support charts that are inside nested directories e.g.
```bash
$ helm center packaging/foo/bar
cat: packagingfoobar/Chart.yaml: No such file or directory
Chart version is not found in Chart.yaml!
Error: plugin "center" exited with error
```

The change enables to find `Chart.yaml` within nested directories.